apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: bank-app:latest
          ports:
            - containerPort: 8080
